# Generated by Django 4.2.5 on 2023-09-16 06:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('full_name', models.CharField(max_length=255, verbose_name='полное имя')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='вес')),
                ('dollar_cost', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='стоимость в долларах')),
                ('ruble_cost', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='стоимость в рублях')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.deliverytype', verbose_name='тип')),
            ],
        ),
    ]
