# Generated by Django 4.2.5 on 2023-09-16 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='dollar_cost',
        ),
        migrations.AddField(
            model_name='delivery',
            name='content_cost',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)], verbose_name='стоимость содержимого в долларах'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery',
            name='weight',
            field=models.PositiveSmallIntegerField(verbose_name='вес в киллограммах'),
        ),
    ]
