# Generated by Django 4.2.5 on 2023-09-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_rename_ruble_cost_delivery_delivery_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='company_id',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='id транспортной компании'),
        ),
    ]
