# Generated by Django 4.2.5 on 2023-09-21 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_delivery_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='content_cost',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='стоимость содержимого в долларах'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_cost',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='стоимость в рублях'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='вес в киллограммах'),
        ),
    ]
