version: '3.8'

services:
  web:
    image: web_image
    build: .
    command: gunicorn international_delivery.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - static_volume:/usr/src/app/staticfiles
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
      - mongodb
      - redis
      - rabbitmq

  db:
    image: mysql:latest
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    command: ["redis-server", "--bind", "redis", "--port", "6380"]
    ports:
      - '6380:6380'

  celery-worker:
    image: web_image
    command: ['celery', '-A', 'international_delivery', 'worker', '-B', '-l', info]
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - mongodb
      - rabbitmq

  mongodb:
    image: mongo:latest
    ports:
      - '27018:27017'
    env_file:
      - .env
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: "rabbitmq:3.8"
    ports:
      - "5673:5672"
      - "15672:15672"
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      
  mq_listener:
    image: web_image
    command: python mq.py
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db
      - mongodb
      - redis
      - rabbitmq
      - web

  web_static:
    image: web_image
    volumes:
      - static_volume:/usr/src/app/staticfiles
    command: python manage.py collectstatic --no-input
    depends_on:
      - web

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
    ports:
      - '8888:80'
    depends_on:
      - web



volumes:
  mysql_data:
  rabbitmq_data:
  mongodb_data:
  static_volume:
