# Generated by Django 4.2.5 on 2023-09-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OuterRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('request_url', models.CharField(max_length=255)),
                ('request_headers', models.TextField(blank=True, null=True)),
                ('request_body', models.TextField(blank=True, null=True)),
                ('response_status_code', models.IntegerField()),
                ('response_headers', models.TextField()),
                ('response_body', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
